# Generated by Django 5.1.3 on 2024-11-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mortuary_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('dod', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('cause_of_death', models.CharField(max_length=250)),
                ('death_cert_num', models.CharField(max_length=100)),
                ('mortuary_fee', models.FloatField()),
            ],
            options={
                'db_table': 'mortuary_table',
            },
        ),
        migrations.CreateModel(
            name='patient_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file_path', models.FileField(upload_to='reports/')),
                ('doctor_id', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='hmsapp.staffdetails')),
            ],
            options={
                'db_table': 'patient_reports',
            },
        ),
        migrations.CreateModel(
            name='Patientdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('patientid', models.CharField(max_length=255)),
                ('regdate', models.CharField(max_length=150)),
                ('docname', models.CharField(blank=True, max_length=255, null=True)),
                ('empid', models.CharField(max_length=100)),
                ('presc', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=1000)),
                ('phnumber', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
                ('dob', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=255)),
                ('guardian', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('mobnumber', models.CharField(max_length=50)),
                ('documentsubmitted', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=50)),
                ('maritialstatus', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('relativetype', models.CharField(blank=True, max_length=200, null=True)),
                ('relativecontactnum', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_reports', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'db_table': 'patientdetails',
                'unique_together': {('id', 'patientid')},
            },
        ),
    ]
