# Generated by Django 5.1.3 on 2024-11-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortuaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('dod', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cause_of_death', models.TextField()),
                ('death_cert_num', models.CharField(max_length=20, unique=True)),
                ('mortuary_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'mortuary_table',
            },
        ),
    ]
