# Generated by Django 5.1.3 on 2024-11-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_ambulance_ambulancealerts_authgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
