# Generated by Django 5.1.3 on 2024-11-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_mortuarytable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MortuaryTable',
            new_name='mortuary_table',
        ),
    ]
