# Generated by Django 5.1.3 on 2024-11-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0003_alter_department_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mortuary_table',
            options={},
        ),
    ]
