# Generated by Django 5.1.3 on 2024-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_alter_mortuary_table_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortuary_table',
            name='dod',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mortuary_table',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
