# Generated by Django 5.1.3 on 2024-11-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_alter_mortuary_table_dod_alter_mortuary_table_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortuary_table',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mortuary_table',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
